/**
* @File Name : MyTestClass.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : March 11, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | March 11, 2025 |   | Initial Version
**/

public class MyTestClass {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}